In [29]:
#6/5/2026 Wednessday

import pandas as pd
import numpy as np

In [30]:
#create messy raw data
#This dataset is in dictionary data type => key : value pairs
data = {
    "EmpId": [101, 102, "103", 104, 105, 106, 107, 108, 109, 110],
    "fullName": [
        "  Alice Johnson  ", "MICHEAL smith", "sarah lee", "David-Kim", None, "john brown",
        "Emma Wilson", "TOM  davis", "Jane Miller", "Chris taylor"
    ], 
     "Dept": ["IT", "hr", "Mktng", "IT", "Customer Care", "marketing", "Finance", None, "HR", "marketing"],
    "Age": [29, "thirty-five", 26, 31, 42, 27, 33, 30, None, 28],
    "Salary($)": ["$5500.50", "4800", "4200.75", "NaN", "6100", "4,300", "5800", "5000", "4700.0", "4400"],
    "JoinDate" : [ 
        "12-04-2021" , "2020.11.01" , "Jan 18, 2022" , "2019/9/25" , "07/05/18" , "2021-10-14" , 
        "2019/12/01" , "2020-03-22" , "May 10th, 2021" , "2022-02-05" 
    ],
    "Performance": [87, "73", 90, 65, 82, 75, 88, None, "79%", "91"],
    "Remote?": ["Yes", "No", "Y", "N", "yes", "no", "Y", "Yes", None, "True"]
}

In [31]:
# To convert raw data set to dataframe dataset
data_frame = pd.DataFrame(data)

data_frame

,EmpId,fullName,Dept,Age,Salary($),JoinDate,Performance,Remote?
0,101,Alice Johnson,IT,29,$5500.50,12-04-2021,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020.11.01,73,No
2,103,sarah lee,Mktng,26,4200.75,"Jan 18, 2022",90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,07/05/18,82,yes
5,106,john brown,marketing,27,"4,300",2021-10-14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,TOM davis,NaN,30,5000,2020-03-22,None,Yes
8,109,Jane Miller,HR,None,4700.0,"May 10th, 2021",79%,NaN
9,110,Chris taylor,marketing,28,4400,2022-02-05,91,True

In [32]:
# Convert dataframe into csv file  to_csv()
# Create a folder (data) on your vs code to save the employee_dataset in a folder
# You can also save it without creating any folder, just that you won't add data to the instruction given to your code. 
# index=False => not to include the index numbers 

data_frame.to_csv("data/employee_dataset.csv", index=False)

In [33]:
# Load a csv file on pandas
# every file has its own loading format
# csv => read_csv()
# excel => read_excel()

#Load csv file dataset on pandas 
df = pd.read_csv("data/employee_dataset.csv")

df

,EmpId,fullName,Dept,Age,Salary($),JoinDate,Performance,Remote?
0,101,Alice Johnson,IT,29,$5500.50,12-04-2021,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020.11.01,73,No
2,103,sarah lee,Mktng,26,4200.75,"Jan 18, 2022",90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,07/05/18,82,yes
5,106,john brown,marketing,27,"4,300",2021-10-14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,TOM davis,NaN,30,5000,2020-03-22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.0,"May 10th, 2021",79%,NaN
9,110,Chris taylor,marketing,28,4400,2022-02-05,91,True

In [34]:
# Explore and data cleaning   .info()
#check the info of the dataset 

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmpId        10 non-null     int64
 1   fullName     9 non-null      str
 2   Dept         9 non-null      str
 3   Age          9 non-null      str
 4   Salary($)    9 non-null      str
 5   JoinDate     10 non-null     str
 6   Performance  9 non-null      str
 7   Remote?      9 non-null      str
dtypes: int64(1), str(7)
memory usage: 772.0 bytes

In [35]:
#Shape will let you known the numbers of rows and colunms you have in the dataset
#Shape(row, colunm)  .shape

df.shape

(10, 8)

In [36]:
# To display part of the dataset 
# get the fisrt five rows from the dataset => .head() 
# pass the number of the data set you want to view in to the .head(10), if its less than or more than 5 bcos 5 is the default value.
df.head()

,EmpId,fullName,Dept,Age,Salary($),JoinDate,Performance,Remote?
0,101,Alice Johnson,IT,29,$5500.50,12-04-2021,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020.11.01,73,No
2,103,sarah lee,Mktng,26,4200.75,"Jan 18, 2022",90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,07/05/18,82,yes

In [37]:
#get the dataset colunms  => .columns
df.columns

Index(['EmpId', 'fullName', 'Dept', 'Age', 'Salary($)', 'JoinDate',
       'Performance', 'Remote?'],
      dtype='str')

In [38]:
#check missing value  => .isnull()

# To calculate the total missing values in the dataset  =>  .isnull().sum()
df.isnull().sum()

# To list theS missing values in the dataset  =>  .isnull()
df.isnull()

   EmpId  fullName   Dept    Age  Salary($)  JoinDate  Performance  Remote?
0  False     False  False  False      False     False        False    False
1  False     False  False  False      False     False        False    False
2  False     False  False  False      False     False        False    False
3  False     False  False  False       True     False        False    False
4  False      True  False  False      False     False        False    False
5  False     False  False  False      False     False        False    False
6  False     False  False  False      False     False        False    False
7  False     False   True  False      False     False         True    False
8  False     False  False   True      False     False        False     True
9  False     False  False  False      False     False        False    False

In [39]:
#inspect unique values in colunms
#pandas represents none value as nan (NaN) and blank space as nan (NaN)
print(df["Dept"].unique())
print(df["Age"].unique())
print(df["Remote?"].unique())

<StringArray>
['IT', 'hr', 'Mktng', 'Customer Care', 'marketing', 'Finance', nan, 'HR']
Length: 8, dtype: str
<StringArray>
['29', 'thirty-five', '26', '31', '42', '27', '33', '30', nan, '28']
Length: 10, dtype: str
<StringArray>
['Yes', 'No', 'Y', 'N', 'yes', 'no', nan, 'True']
Length: 8, dtype: str

In [40]:
#access salary value 
# series format  df["Salary($)"]
# list format df["Salary($)"].to_list()
df["Salary($)"].to_list()

['$5500.50',
 '4800',
 '4200.75',
 nan,
 '6100',
 '4,300',
 '5800',
 '5000',
 '4700.0',
 '4400']

In [41]:
#7/5/2026 Thursday
df["fullName"].to_list()

['  Alice Johnson  ',
 'MICHEAL smith',
 'sarah lee',
 'David-Kim',
 nan,
 'john brown',
 'Emma Wilson',
 'TOM  davis',
 'Jane Miller',
 'Chris taylor']

In [42]:
df["Salary($)"].head()

0    $5500.50
1        4800
2     4200.75
3         NaN
4        6100
Name: Salary($), dtype: str

In [43]:
#Data cleaning 
#

df.rename(columns={
    "EmpId" : "Employment ID" , 
    "fullName" : "Full Name" ,
    "Dept" : "Department" ,
    "Age" : "Age" ,
    "Salary($)" : "Salary" ,
    "JoinDate" : "Join Date" ,
    "Performance" : "Performance" ,
    "Remote?" : "Remote"
} , inplace=True)

df

,Employment ID,Full Name,Department,Age,Salary,Join Date,Performance,Remote
0,101,Alice Johnson,IT,29,$5500.50,12-04-2021,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020.11.01,73,No
2,103,sarah lee,Mktng,26,4200.75,"Jan 18, 2022",90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,07/05/18,82,yes
5,106,john brown,marketing,27,"4,300",2021-10-14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,TOM davis,NaN,30,5000,2020-03-22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.0,"May 10th, 2021",79%,NaN
9,110,Chris taylor,marketing,28,4400,2022-02-05,91,True

In [44]:
#Cleaning inconsistence values on full name
df["Full Name"].to_list()

['  Alice Johnson  ',
 'MICHEAL smith',
 'sarah lee',
 'David-Kim',
 nan,
 'john brown',
 'Emma Wilson',
 'TOM  davis',
 'Jane Miller',
 'Chris taylor']

In [45]:
# .strip() is used to remove spaces before and after from the strings object
# .title is used to capitalized first letter in a character
# .replace to replace a value 
# (r"[\s-]+", " ", regex=True)
# .str mean strings
df["Full Name"] = (
    df["Full Name"]
    .str.strip()
    .str.title()
    .str.replace(r"[\s-]+", " ", regex=True)
)
df["Full Name"].to_list()

['Alice Johnson',
 'Micheal Smith',
 'Sarah Lee',
 'David Kim',
 nan,
 'John Brown',
 'Emma Wilson',
 'Tom Davis',
 'Jane Miller',
 'Chris Taylor']

In [46]:
#Cleaning inconsistence values on Department
df["Department"].to_list()

['IT',
 'hr',
 'Mktng',
 'IT',
 'Customer Care',
 'marketing',
 'Finance',
 nan,
 'HR',
 'marketing']

In [47]:
# replace 

df.replace({
    "hr" : "HR",
    "Mktng" : "Marketing",
    "marketing" : "Marketing",
    None : np.nan
}, inplace=True)

df["Department"]

0               IT
1               HR
2        Marketing
3               IT
4    Customer Care
5        Marketing
6          Finance
7              NaN
8               HR
9        Marketing
Name: Department, dtype: str

In [48]:
# Cleaning inconsistence value in Age
df["Age"].to_list()

['29', 'thirty-five', '26', '31', '42', '27', '33', '30', nan, '28']

In [49]:
# Custom function to clean a 
# .apply() function will allow the changes on pandas

def clean_age(value): 
    if value == "thirty-five":
        return 35
    elif isinstance(value, (int, float)):
        return value
    elif isinstance(value, str) and value.isdigit():
        return int(value)
    else:
        return np.nan

df["Age"] = df["Age"].apply(clean_age)

df["Age"]

0    29.0
1    35.0
2    26.0
3    31.0
4    42.0
5    27.0
6    33.0
7    30.0
8     NaN
9    28.0
Name: Age, dtype: float64

In [50]:
# assignment 
# Clean Salary, Performance and remote

In [51]:
#Cleaning inconsistence value in Salary
df["Salary"].to_list()

['$5500.50',
 '4800',
 '4200.75',
 nan,
 '6100',
 '4,300',
 '5800',
 '5000',
 '4700.0',
 '4400']

In [52]:
#Cleaning inconsistence value in Salary
df["Salary"] = (
    df["Salary"]
    .str.replace(r"[\$,]+", "", regex=True)
)

df["Salary"]

0    5500.50
1       4800
2    4200.75
3        NaN
4       6100
5       4300
6       5800
7       5000
8     4700.0
9       4400
Name: Salary, dtype: str

In [53]:
#Cleaning inconsistence value in Performance
df["Performance"].to_list()

['87', '73', '90', '65', '82', '75', '88', nan, '79%', '91']

In [68]:
#Cleaning inconsistence value in Performance

df["Performnace"] = (
    df["Performance"]
    .str.replace(r"%", "", regex=True)

)

df["Performnace"]

0     87
1     73
2     90
3     65
4     82
5     75
6     88
7    NaN
8     79
9     91
Name: Performnace, dtype: str

In [57]:
#Cleaning inconsistence value in Performance

df["Remote"].to_list()

['Yes', 'No', 'Y', 'N', 'yes', 'no', 'Y', 'Yes', nan, 'True']

In [63]:
#Cleaning inconsistence value in Performance

df["Remote"] = (
    df["Remote"]
    .replace({
        "Y" : "Yes",
        "N" : "No",
        "yes" : "Yes",
        "no" : "No"
    } ))
df["Remote"]

0     Yes
1      No
2     Yes
3      No
4     Yes
5      No
6     Yes
7     Yes
8     NaN
9    True
Name: Remote, dtype: str

In [69]:
df

,Employment ID,Full Name,Department,Age,Salary,Join Date,Performance,Remote,Performnace
0,101,Alice Johnson,IT,29.0,5500.50,12-04-2021,87,Yes,87
1,102,Micheal Smith,HR,35.0,4800,2020.11.01,73,No,73
2,103,Sarah Lee,Marketing,26.0,4200.75,"Jan 18, 2022",90,Yes,90
3,104,David Kim,IT,31.0,NaN,2019/9/25,65,No,65
4,105,NaN,Customer Care,42.0,6100,07/05/18,82,Yes,82
5,106,John Brown,Marketing,27.0,4300,2021-10-14,75,No,75
6,107,Emma Wilson,Finance,33.0,5800,2019/12/01,88,Yes,88
7,108,Tom Davis,NaN,30.0,5000,2020-03-22,NaN,Yes,NaN
8,109,Jane Miller,HR,NaN,4700.0,"May 10th, 2021",79%,NaN,79
9,110,Chris Taylor,Marketing,28.0,4400,2022-02-05,91,True,91